name: Code style

on: [ pull_request ]

jobs:
  lint:
    name: all linters
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: rubocop
        run: bin/ontoportal run bundle exec rubocop --parallel
