# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby
name: "Run remote API (stageportal) tests CI"

on:
  push:
  pull_request:
    types: [ opened, reopened ]
env:
  API_URL: https://data.stageportal.lirmm.fr/ # or ${{ secrets.API_URL }}
  API_KEY: 1de0a270-29c5-4dda-b043-7c3580628cd5 # public apikey or ${{ secrets.API_KEY }}
  BIOMIXER_URL: ${{ secrets.BIOMIXER_URL }}
  FAIRNESS_URL: ${{ secrets.FAIRNESS_URL }}
  ANNOTATOR_URL: ${{ secrets.ANNOTATOR_URL }}
  DB_HOST: 127.0.0.1
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: root
      memcached:
        image: memcached:1.6
        ports:
          - 11211:11211
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          bundler-cache: true
      # Add or replace database setup steps here
      - name: set up config file
        run: cp config/database.yml.sample config/database.yml
      - name: Set up database schema
        run: RAILS_ENV=test bin/rails db:setup
      - name: Set up yarn
        run: yarn install
      # Add or replace test runners here
      - name: Run tests
        run:  RAILS_ENV=test bin/rails test test/controllers/* -v