name: RuboCop

on: [push, pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 # You can change this to your preferred Ruby version

      - name: Install RuboCop
        run:
          gem install rubocop rubocop-rails

      - name: Run RuboCop
        run: rubocop --parallel --format github
